export const achivements = [
  {
    img: "/img/archivements/Introduction to DevOps.png",
    title: "DevOps Fundamentals",
    body: "Introduction to DevOps",
    date: "April 06, 2026",
    link: "https://drive.google.com/file/d/1DLOhZ0pSe8v3e_EsVVh6A9Qa4tGLzsWk/view?usp=sharing",
  },
  {
    img: "/img/archivements/Python Essentials 2.png",
    title: "Python Essentials",
    body: "Python Essentials 2",
    date: "April 07, 2026",
    link: "https://drive.google.com/file/d/1-Hzq-UAiDhkUdZ7LspKDIN5HsStEc0l2/view?usp=sharing",
  },
  {
    img: "/img/archivements/Python Essentials 1.png",
    title: "Python Essentials",
    body: "Python Essentials 1",
    date: "February 19, 2026",
    link: "https://drive.google.com/file/d/1OpayUwHpEWC_LVi2mSlZT6wtxQy5DLjS/view?usp=sharing",
  },
  {
    img: "/img/archivements/cybersecurity.png",
    title: "Cybersecurity",
    body: "Introduction to Cybersecurity",
    bodyKey: "ach.cybersecurity.body",
    date: "November 03, 2024",
    link: "https://drive.google.com/file/d/1_bmQsga2yVHQXWOIFWbqQ-P-Z26J-k_b/view?usp=drive_link",
  },
  {
    img: "/img/archivements/AI Fundamentals.png",
    title: "AI",
    body: "AI Fundamentals",
    date: "November 15, 2024",
    link: "https://drive.google.com/file/d/1wLG311guenZzt0kmB3-tAAOHtrXpDoOT/view?usp=drive_link",
  },
  {
    img: "/img/archivements/java.jpg",
    title: "JAVA Programming degree",
    body: "Java Basics",
    bodyKey: "ach.java.body",
    date: "March 30, 2024",
    link: "https://drive.google.com/file/d/1AJMvviNfzwzL0hZ7eOiSsyGKMjD--q_i/view?usp=drive_link",
  },
  {
    img: "/img/archivements/php.jpg",
    title: "PHP Programming degree",
    body: "PHP Basics",
    bodyKey: "ach.php.body",
    date: "April 13, 2024",
    link: "https://drive.google.com/file/d/1gSxeQOg0VHJW0eScWqIuftrP86sp96ac/view?usp=drive_link",
  },
  {
    img: "/img/archivements/CSEI 24 PAPER 9 Presentation.png",
    title: "Emerging Research Frontiers in Computer Science, Electronics and Industrial Engineering",
    body: "CSEI 24 PAPER 9",
    date: "October 25, 2024",
    link: "https://drive.google.com/file/d/1rRLd2yZk8c5z8TigoyYGJILH1tX2ucny/view?usp=drive_link",
  },
  {
    img: "/img/archivements/EthicalHacking.jpg",
    title: "Ethical Hacking | Red Team 2da edición",
    body: "Hacker Mentor",
    date: "October 10, 2022",
    link: "https://drive.google.com/file/d/1lUI-zu6I4ndb7P4Md3bqWhmolun4cFHi/view?usp=drive_link",
  },
];
